### PR TITLE
Make memory cards being disabled

### PR DESCRIPTION
**Pull request by EhotPotaskun**
Fixes Codename: Tenka startup banner "Please remove one of the memory cards"
Also fixes "++slot > 15" and "(--slot < 0) = slot 15" instead of 16. Typo?

### CODE REVIEW

**Comment by EhotPotaskun** [comment]
Nah, i broke something with last changes. Needs additional testing as well

**Comment by EhotPotaskun** [comment]
Rewrited entirely and it's working

**Comment by jdgleaver** [comment]
Thank you for this!

There are just a couple of things:

- Why do we need a new `Memory card Slots` option? It seems we could implement this using only `McdSlot1`/`McdSlot2`
- We need to maintain slot index 0 as the `per-game` memory card setting. We want to keep this as the default, and changing the index will break existing config files. Would you be wiling to swap the functionality of indices 0 and 17 here?

**Comment by EhotPotaskun** [comment]
There are already some code in sio.cpp, which makes Memory Card being disabled if its path is zeroed
I was trying to make everything up without new **McdSlots**, with 0 (disabled) and 17 (per-game) values in Config.McdSlot1/2, but there is nasty bug up there - every time i set Config.McdSlot1/2 to 0 it creates unwanted mcd000.mcr file.

If there's any less complicacted way to do so i'm all ears

**Comment by jdgleaver** [comment]
> I was trying to make everything up without new McdSlots, with 0 (disabled) and 17 (per-game) values in Config.McdSlot1/2, but there is nasty bug up there - every time i set Config.McdSlot1/2 to 0 it creates unwanted mcd000.mcr file.

But why should it create an unnecessary file? If McdSlot1/2 is 'disabled', it should zero the path automatically, and prevent a file from being written. I don't think we need an extra flag for this.

Also, we really can't change the meaning of `0` to `disabled` - existing config files must remain compatible!

**Comment by EhotPotaskun** [comment]
Well feel free to change anything you wish!
I'm not such a good programmer I should say 😉

**Comment by jdgleaver** [comment]
Ah, that is fine! No problem at all :)

I shall have a think about the best way to go about implementing this. Many thanks for providing me with some nice code to work with - and for highlighting this issue in the first place! I have never played Codename: Tenka, and so didn't know that it was broken like this (I'm sure there must be other games that are affected as well).

**Comment by EhotPotaskun** [comment]
There is the only fork I know with implemented fix for that game, but it brings really complicated automated solution of comparing an inserted disc ID with list of Tenka's one (like SCUS_944.09)

But i personally like it in more clear and controllable way, same way it implemented in RetroArch for example.

And after all Tenka is a so nostalgic one for me and really well crafted game for it's time, such nice reason to finally give it a try! :)

Oh yeah, and thanks for your support! 
Cheers

**Comment by jdgleaver** [comment]
@EhotPotaskun I've implemented this using the simplest method I can think of in a feature branch here: https://github.com/jdgleaver/RG350_pcsx4all/tree/disable-memcard

Would you like to double check it? (I've tested Tenka, but it's always nice to have a second pair of eyes on these things!)

**Comment by EhotPotaskun** [comment]
Yeah, sure!

**Comment by jdgleaver** [comment]
Thanks!

I need to log off shortly, but if all is well I will try to push a new release tomorrow :)

**Comment by EhotPotaskun** [comment]
As far as I see it works flawlessly both in Tenka and in BIOS Memory card manager

**Comment by jdgleaver** [comment]
Great! Thanks for testing this - much appreciated :)

**Pull request closed without merging**
